In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv(r'C:\Users\SHYAM SASHANK\OneDrive\Desktop\Data_Science\Assginment_CSV\Fraud_check.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Undergrad        600 non-null    object
 1   Marital.Status   600 non-null    object
 2   Taxable.Income   600 non-null    int64
 3   City.Population  600 non-null    int64
 4   Work.Experience  600 non-null    int64
 5   Urban            600 non-null    object
dtypes: int64(3), object(3)
memory usage: 28.2+ KB

In [4]:
df1=pd.get_dummies(df)
df1

,Taxable.Income,City.Population,Work.Experience,Undergrad_NO,Undergrad_YES,Marital.Status_Divorced,Marital.Status_Married,Marital.Status_Single,Urban_NO,Urban_YES
0,68833,50047,10,1,0,0,0,1,0,1
1,33700,134075,18,0,1,1,0,0,0,1
2,36925,160205,30,1,0,0,1,0,0,1
3,50190,193264,15,0,1,0,0,1,0,1
4,81002,27533,28,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...
595,76340,39492,7,0,1,1,0,0,0,1
596,69967,55369,2,0,1,1,0,0,0,1
597,47334,154058,0,1,0,1,0,0,0,1
598,98592,180083,17,0,1,0,1,0,1,0
599,96519,158137,16,1,0,1,0,0,1,0

In [5]:
df1.isnull()

,Taxable.Income,City.Population,Work.Experience,Undergrad_NO,Undergrad_YES,Marital.Status_Divorced,Marital.Status_Married,Marital.Status_Single,Urban_NO,Urban_YES
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
595,False,False,False,False,False,False,False,False,False,False
596,False,False,False,False,False,False,False,False,False,False
597,False,False,False,False,False,False,False,False,False,False
598,False,False,False,False,False,False,False,False,False,False
599,False,False,False,False,False,False,False,False,False,False

In [6]:
x=df1.drop(columns="Taxable.Income")
x.head()

,City.Population,Work.Experience,Undergrad_NO,Undergrad_YES,Marital.Status_Divorced,Marital.Status_Married,Marital.Status_Single,Urban_NO,Urban_YES
0,50047,10,1,0,0,0,1,0,1
1,134075,18,0,1,1,0,0,0,1
2,160205,30,1,0,0,1,0,0,1
3,193264,15,0,1,0,0,1,0,1
4,27533,28,1,0,0,1,0,1,0

In [7]:
y=df1[["Taxable.Income"]]
y.head()

   Taxable.Income
0           68833
1           33700
2           36925
3           50190
4           81002

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.3, random_state=20)

In [10]:
X_train

,City.Population,Work.Experience,Undergrad_NO,Undergrad_YES,Marital.Status_Divorced,Marital.Status_Married,Marital.Status_Single,Urban_NO,Urban_YES
325,25779,16,1,0,0,0,1,0,1
553,26884,13,1,0,0,0,1,0,1
582,32907,12,0,1,0,1,0,0,1
488,76718,10,0,1,0,0,1,0,1
496,59382,5,0,1,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...
218,38091,19,1,0,0,1,0,1,0
223,192297,17,0,1,0,1,0,0,1
271,183682,20,1,0,0,0,1,1,0
474,80729,0,0,1,1,0,0,1,0
355,56488,17,0,1,0,0,1,1,0

In [11]:
X_test

,City.Population,Work.Experience,Undergrad_NO,Undergrad_YES,Marital.Status_Divorced,Marital.Status_Married,Marital.Status_Single,Urban_NO,Urban_YES
493,103226,29,1,0,0,1,0,1,0
172,52819,23,1,0,0,1,0,0,1
352,72115,16,1,0,1,0,0,0,1
506,111105,8,1,0,0,0,1,0,1
595,39492,7,0,1,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...
508,195357,19,1,0,0,0,1,1,0
476,183057,7,1,0,0,0,1,0,1
475,36081,12,1,0,0,0,1,0,1
235,87541,9,1,0,1,0,0,1,0
89,176050,20,0,1,0,1,0,1,0

In [12]:
Y_train

     Taxable.Income
325           94013
553           91462
582           84931
488           86883
496           72151
..              ...
218           57794
223           38374
271           42254
474           99128
355           45525

[420 rows x 1 columns]

In [13]:
Y_test

     Taxable.Income
493           17183
172           13068
352           15627
506           23884
595           76340
..              ...
508           46002
476           79478
475           35868
235           77735
89            26741

[180 rows x 1 columns]

In [14]:
from sklearn.ensemble import RandomForestClassifier

In [15]:
model = RandomForestClassifier(n_estimators=100, random_state=42)

In [16]:
model.fit(X_train,Y_train)

RandomForestClassifier(random_state=42)

In [17]:
y_pred_train=model.predict(X_train)
y_pred_train

array([94013, 91462, 84931, 86883, 72151, 67628, 76700, 71238, 20109,
       57445, 30468, 92426, 55308, 68911, 45706, 44034, 93733, 55299,
       76992, 70743, 31721, 41344, 70645, 78963, 72115, 86958, 41395,
       57402, 54747, 91488, 34475, 78969, 51802, 80239, 59440, 54638,
       32662, 97980, 77312, 32786, 51028, 14422, 90444, 46955, 36532,
       48081, 75585, 95088, 79869, 16992, 48169, 43865, 10987, 29222,
       36317, 99307, 82625, 59243, 22773, 22159, 62365, 56628, 86079,
       12659, 95145, 26101, 12011, 77367, 56974, 59860, 13571, 14398,
       91220, 36457, 78400, 33356, 56501, 89277, 71164, 93364, 77511,
       68617, 64614, 28904, 75324, 46629, 98738, 32483, 26793, 86652,
       43980, 98334, 13747, 73188, 24370, 39144, 26972, 14912, 90945,
       72268, 62998, 36239, 34833, 56129, 36890, 98433, 41641, 75170,
       71297, 11804, 60789, 59227, 81378, 31085, 41117, 31417, 64225,
       10379, 28764, 68756, 70298, 22187, 32905, 47364, 97453, 63710,
       50777, 27081, 10870, 23480, 70526, 69018, 94247, 27143, 17962,
       38670, 59689, 38626, 42507, 69224, 31521, 46939, 55981, 87348,
       48738, 46470, 54126, 61906, 12810, 62426, 17783, 21016, 50242,
       96355, 68152, 90910, 50119, 88613, 51927, 40220, 46610, 41545,
       39444, 84775, 79373, 21337, 15853, 54345, 52912, 33215, 36156,
       87677, 98720, 27394, 27698, 33116, 18032, 10163, 32603, 15491,
       94413, 94583, 20719, 31591, 89250, 39562, 44795, 14300, 56438,
       78728, 24215, 95319, 81939, 34655, 52022, 28449, 70157, 99619,
       84836, 69869, 33329, 70682, 18888, 92070, 74010, 59689, 16264,
       83061, 19649, 52111, 83094, 52495, 71357, 10735, 39818, 41382,
       84083, 23075, 42063, 52862, 97341, 50087, 48640, 81536, 27684,
       11784, 35886, 81002, 21696, 48313, 31633, 10933, 64437, 33492,
       73313, 57365, 63912, 33700, 18572, 51913, 98416, 29916, 38896,
       68269, 48392, 41087, 33614, 62800, 71376, 25062, 42488, 89302,
       61105, 30167, 50403, 29607, 68696, 86208, 42679, 79616, 25222,
       93458, 61445, 12470, 62158, 92007, 83459, 48779, 93090, 35832,
       93659, 59615, 42769, 33138, 19060, 87778, 87326, 61063, 66330,
       12083, 58496, 94528, 92997, 98588, 98240, 61486, 58403, 16320,
       77762, 89831, 85076, 99109, 47565, 22258, 95185, 79593, 15710,
       11794, 42784, 93078, 40137, 35200, 10003, 58312, 19925, 70572,
       22054, 10900, 94418, 62067, 64320, 77082, 84835, 91870, 96032,
       50348, 79583, 12453, 16316, 67083, 65190, 25766, 31699, 29385,
       40427, 59419, 42483, 14326, 84429, 24541, 10150, 68513, 39277,
       72949, 68533, 18199, 76182, 37481, 63543, 20851, 33810, 49436,
       18192, 72382, 35072, 69967, 54502, 46070, 49958, 58635, 33301,
       82799, 93307, 62209, 49995, 52891, 32356, 80083, 31088, 58199,
       86784, 28707, 98933, 21966, 68268, 38704, 28496, 26679, 66564,
       68404, 38183, 98970, 84691, 66865, 73411, 54850, 69540, 32900,
       32948, 99239, 33748, 51363, 96485, 16690, 81231, 44411, 87935,
       32236, 43018, 10329, 84557, 70339, 37580, 20309, 24347, 58451,
       12072, 73795, 42074, 56536, 97111, 64667, 83357, 38143, 94772,
       79453, 73620, 98592, 84845, 89094, 29944, 56503, 69036, 91545,
       30714, 57794, 38374, 42254, 99128, 45525], dtype=int64)

In [18]:
y_pred_test=model.predict(X_test)
y_pred_test

array([94413, 78400, 87348, 34833, 64320, 74010, 81002, 98416, 64614,
       43018, 86652, 31721, 26101, 71238, 54126, 38374, 90910, 87348,
       33614, 14398, 18888, 70645, 18572, 15491, 68696, 64437, 62998,
       29916, 19649, 21696, 11794, 10870, 94413, 50348, 28904, 73620,
       14300, 27698, 55299, 63912, 98240, 12470, 41117, 71297, 41545,
       94418, 79373, 59689, 99307, 40220, 46955, 87348, 70526, 24541,
       31699, 96355, 39144, 48392, 78963, 81536, 61063, 62426, 99307,
       36532, 63912, 70743, 33215, 83061, 56628, 44034, 18032, 90910,
       42679, 98592, 59615, 84557, 52891, 33116, 10735, 90910, 42507,
       63543, 63912, 54638, 47565, 69869, 46955, 14422, 98738, 84429,
       23075, 31721, 93659, 70572, 77511, 16690, 69018, 10379, 50777,
       68617, 21016, 38183, 71357, 63710, 32948, 68756, 58451, 84845,
       42254, 36239, 13747, 71238, 41344, 84775, 36532, 41641, 11794,
       92426, 91545, 40220, 50242, 36239, 95088, 97453, 90444, 33215,
       17962, 12659, 89277, 62998, 97453, 66564, 16690, 70339, 42679,
       12470, 86208, 78400, 70157, 70645, 42254, 62426, 16690, 62067,
       32236, 29222, 54345, 46955, 69224, 33614, 69540, 41395, 25766,
       31699, 21696, 59243, 20309, 46470, 84083, 33356, 93307, 54502,
       68756, 21016, 81002, 87348, 26972, 79616, 84691, 83061, 73188,
       91545, 81231, 30714, 39818, 42254, 92426, 91462, 24541, 98592],
      dtype=int64)

In [19]:
from sklearn.metrics import classification_report

print(classification_report(y_pred_test,Y_test))

              precision    recall  f1-score   support

       10348       0.00      0.00      0.00       0.0
       10379       0.00      0.00      0.00       1.0
       10455       0.00      0.00      0.00       0.0
       10735       0.00      0.00      0.00       1.0
       10870       0.00      0.00      0.00       1.0
       11794       0.00      0.00      0.00       2.0
       11865       0.00      0.00      0.00       0.0
       12470       0.00      0.00      0.00       2.0
       12514       0.00      0.00      0.00       0.0
       12659       0.00      0.00      0.00       1.0
       12682       0.00      0.00      0.00       0.0
       13068       0.00      0.00      0.00       0.0
       13747       0.00      0.00      0.00       1.0
       14300       0.00      0.00      0.00       1.0
       14310       0.00      0.00      0.00       0.0
       14398       0.00      0.00      0.00       1.0
       14422       0.00      0.00      0.00       1.0
       15296       0.00      0.00      0.00       0.0
       15491       0.00      0.00      0.00       1.0
       15532       0.00      0.00      0.00       0.0
       15627       0.00      0.00      0.00       0.0
       15673       0.00      0.00      0.00       0.0
       16082       0.00      0.00      0.00       0.0
       16690       0.00      0.00      0.00       3.0
       17183       0.00      0.00      0.00       0.0
       17440       0.00      0.00      0.00       0.0
       17957       0.00      0.00      0.00       0.0
       17962       0.00      0.00      0.00       1.0
       18032       0.00      0.00      0.00       1.0
       18572       0.00      0.00      0.00       1.0
       18888       0.00      0.00      0.00       1.0
       19169       0.00      0.00      0.00       0.0
       19184       0.00      0.00      0.00       0.0
       19272       0.00      0.00      0.00       0.0
       19649       0.00      0.00      0.00       1.0
       20309       0.00      0.00      0.00       1.0
       20391       0.00      0.00      0.00       0.0
       20604       0.00      0.00      0.00       0.0
       21016       0.00      0.00      0.00       2.0
       21696       0.00      0.00      0.00       2.0
       21917       0.00      0.00      0.00       0.0
       21945       0.00      0.00      0.00       0.0
       23075       0.00      0.00      0.00       1.0
       23855       0.00      0.00      0.00       0.0
       23884       0.00      0.00      0.00       0.0
       24541       0.00      0.00      0.00       2.0
       24557       0.00      0.00      0.00       0.0
       24987       0.00      0.00      0.00       0.0
       25766       0.00      0.00      0.00       1.0
       26094       0.00      0.00      0.00       0.0
       26101       0.00      0.00      0.00       1.0
       26128       0.00      0.00      0.00       0.0
       26372       0.00      0.00      0.00       0.0
       26494       0.00      0.00      0.00       0.0
       26741       0.00      0.00      0.00       0.0
       26783       0.00      0.00      0.00       0.0
       26972       0.00      0.00      0.00       1.0
       27520       0.00      0.00      0.00       0.0
       27698       0.00      0.00      0.00       1.0
       27877       0.00      0.00      0.00       0.0
       28904       0.00      0.00      0.00       1.0
       29046       0.00      0.00      0.00       0.0
       29222       0.00      0.00      0.00       1.0
       29236       0.00      0.00      0.00       0.0
       29543       0.00      0.00      0.00       0.0
       29732       0.00      0.00      0.00       0.0
       29916       0.00      0.00      0.00       1.0
       30495       0.00      0.00      0.00       0.0
       30714       0.00      0.00      0.00       1.0
       31336       0.00      0.00      0.00       0.0
       31409       0.00      0.00      0.00       0.0
       31458       0.00      0.00      0.00       0.0
       31532       0.00      0.00      0.00       0.0
       31629       0.00      0.00      0.00       0.0
       31645       0.00      0.00      0.00       0.0
       31699       0.00      0.00      0.00       2.0
       31721       0.00      0.00      0.00       2.0
       32236       0.00      0.00      0.00       1.0
       32434       0.00      0.00      0.00       0.0
       32467       0.00      0.00      0.00       0.0
       32948       0.00      0.00      0.00       1.0
       33092       0.00      0.00      0.00       0.0
       33116       0.00      0.00      0.00       1.0
       33215       0.00      0.00      0.00       2.0
       33356       0.00      0.00      0.00       1.0
       33579       0.00      0.00      0.00       0.0
       33614       0.00      0.00      0.00       2.0
       33962       0.00      0.00      0.00       0.0
       34007       0.00      0.00      0.00       0.0
       34598       0.00      0.00      0.00       0.0
       34703       0.00      0.00      0.00       0.0
       34833       0.00      0.00      0.00       1.0
       35610       0.00      0.00      0.00       0.0
       35868       0.00      0.00      0.00       0.0
       35922       0.00      0.00      0.00       0.0
       36239       0.00      0.00      0.00       2.0
       36532       0.00      0.00      0.00       2.0
       36925       0.00      0.00      0.00       0.0
       37857       0.00      0.00      0.00       0.0
       38183       0.00      0.00      0.00       1.0
       38239       0.00      0.00      0.00       0.0
       38374       0.00      0.00      0.00       1.0
       38586       0.00      0.00      0.00       0.0
       38638       0.00      0.00      0.00       0.0
       39052       0.00      0.00      0.00       0.0
       39114       0.00      0.00      0.00       0.0
       39144       0.00      0.00      0.00       1.0
       39343       0.00      0.00      0.00       0.0
       39476       0.00      0.00      0.00       0.0
       39818       0.00      0.00      0.00       1.0
       40220       0.00      0.00      0.00       2.0
       40674       0.00      0.00      0.00       0.0
       41117       0.00      0.00      0.00       1.0
       41184       0.00      0.00      0.00       0.0
       41344       0.00      0.00      0.00       1.0
       41395       0.00      0.00      0.00       1.0
       41545       0.00      0.00      0.00       1.0
       41641       0.00      0.00      0.00       1.0
       42254       0.00      0.00      0.00       3.0
       42507       0.00      0.00      0.00       1.0
       42679       0.00      0.00      0.00       2.0
       43018       0.00      0.00      0.00       1.0
       43051       0.00      0.00      0.00       0.0
       43128       0.00      0.00      0.00       0.0
       43883       0.00      0.00      0.00       0.0
       44034       0.00      0.00      0.00       1.0
       44809       0.00      0.00      0.00       0.0
       44947       0.00      0.00      0.00       0.0
       46002       0.00      0.00      0.00       0.0
       46470       0.00      0.00      0.00       1.0
       46798       0.00      0.00      0.00       0.0
       46955       0.00      0.00      0.00       3.0
       47334       0.00      0.00      0.00       0.0
       47425       0.00      0.00      0.00       0.0
       47565       0.00      0.00      0.00       1.0
       48192       0.00      0.00      0.00       0.0
       48392       0.00      0.00      0.00       1.0
       48825       0.00      0.00      0.00       0.0
       48940       0.00      0.00      0.00       0.0
       49520       0.00      0.00      0.00       0.0
       49771       0.00      0.00      0.00       0.0
       50190       0.00      0.00      0.00       0.0
       50242       0.00      0.00      0.00       1.0
       50286       0.00      0.00      0.00       0.0
       50348       0.00      0.00      0.00       1.0
       50777       0.00      0.00      0.00       1.0
       51685       0.00      0.00      0.00       0.0
       51914       0.00      0.00      0.00       0.0
       52663       0.00      0.00      0.00       0.0
       52891       0.00      0.00      0.00       1.0
       53378       0.00      0.00      0.00       0.0
       53981       0.00      0.00      0.00       0.0
       54126       0.00      0.00      0.00       1.0
       54345       0.00      0.00      0.00       1.0
       54502       0.00      0.00      0.00       1.0
       54638       0.00      0.00      0.00       1.0
       55299       0.00      0.00      0.00       1.0
       55873       0.00      0.00      0.00       0.0
       56166       0.00      0.00      0.00       0.0
       56555       0.00      0.00      0.00       0.0
       56628       0.00      0.00      0.00       1.0
       56647       0.00      0.00      0.00       0.0
       58451       0.00      0.00      0.00       1.0
       58751       0.00      0.00      0.00       0.0
       59243       0.00      0.00      0.00       1.0
       59351       0.00      0.00      0.00       0.0
       59615       0.00      0.00      0.00       1.0
       59689       0.00      0.00      0.00       1.0
       60822       0.00      0.00      0.00       0.0
       60915       0.00      0.00      0.00       0.0
       61063       0.00      0.00      0.00       1.0
       61124       0.00      0.00      0.00       0.0
       61830       0.00      0.00      0.00       0.0
       62067       0.00      0.00      0.00       1.0
       62141       0.00      0.00      0.00       0.0
       62426       0.00      0.00      0.00       2.0
       62494       0.00      0.00      0.00       0.0
       62774       0.00      0.00      0.00       0.0
       62873       0.00      0.00      0.00       0.0
       62998       0.00      0.00      0.00       2.0
       63057       0.00      0.00      0.00       0.0
       63543       0.00      0.00      0.00       1.0
       63710       0.00      0.00      0.00       1.0
       63912       0.00      0.00      0.00       3.0
       64007       0.00      0.00      0.00       0.0
       64070       0.00      0.00      0.00       0.0
       64230       0.00      0.00      0.00       0.0
       64320       0.00      0.00      0.00       1.0
       64437       0.00      0.00      0.00       1.0
       64614       0.00      0.00      0.00       1.0
       65065       0.00      0.00      0.00       0.0
       65170       0.00      0.00      0.00       0.0
       65203       0.00      0.00      0.00       0.0
       66564       0.00      0.00      0.00       1.0
       66905       0.00      0.00      0.00       0.0
       67033       0.00      0.00      0.00       0.0
       67936       0.00      0.00      0.00       0.0
       68617       0.00      0.00      0.00       1.0
       68696       0.00      0.00      0.00       1.0
       68756       0.00      0.00      0.00       2.0
       68833       0.00      0.00      0.00       0.0
       69018       0.00      0.00      0.00       1.0
       69098       0.00      0.00      0.00       0.0
       69224       0.00      0.00      0.00       1.0
       69540       0.00      0.00      0.00       1.0
       69869       0.00      0.00      0.00       1.0
       70157       0.00      0.00      0.00       1.0
       70339       0.00      0.00      0.00       1.0
       70365       0.00      0.00      0.00       0.0
       70526       0.00      0.00      0.00       1.0
       70572       0.00      0.00      0.00       1.0
       70645       0.00      0.00      0.00       2.0
       70712       0.00      0.00      0.00       0.0
       70743       0.00      0.00      0.00       1.0
       70812       0.00      0.00      0.00       0.0
       70819       0.00      0.00      0.00       0.0
       70949       0.00      0.00      0.00       0.0
       71238       0.00      0.00      0.00       2.0
       71297       0.00      0.00      0.00       1.0
       71357       0.00      0.00      0.00       1.0
       71428       0.00      0.00      0.00       0.0
       71572       0.00      0.00      0.00       0.0
       72026       0.00      0.00      0.00       0.0
       73188       0.00      0.00      0.00       1.0
       73620       0.00      0.00      0.00       1.0
       73854       0.00      0.00      0.00       0.0
       73906       0.00      0.00      0.00       0.0
       74010       0.00      0.00      0.00       1.0
       74971       0.00      0.00      0.00       0.0
       75501       0.00      0.00      0.00       0.0
       76340       0.00      0.00      0.00       0.0
       76535       0.00      0.00      0.00       0.0
       77511       0.00      0.00      0.00       1.0
       77634       0.00      0.00      0.00       0.0
       77735       0.00      0.00      0.00       0.0
       78400       0.00      0.00      0.00       2.0
       78573       0.00      0.00      0.00       0.0
       78796       0.00      0.00      0.00       0.0
       78867       0.00      0.00      0.00       0.0
       78922       0.00      0.00      0.00       0.0
       78963       0.00      0.00      0.00       1.0
       79211       0.00      0.00      0.00       0.0
       79357       0.00      0.00      0.00       0.0
       79373       0.00      0.00      0.00       1.0
       79478       0.00      0.00      0.00       0.0
       79616       0.00      0.00      0.00       1.0
       79700       0.00      0.00      0.00       0.0
       80618       0.00      0.00      0.00       0.0
       81002       0.00      0.00      0.00       2.0
       81026       0.00      0.00      0.00       0.0
       81079       0.00      0.00      0.00       0.0
       81231       0.00      0.00      0.00       1.0
       81536       0.00      0.00      0.00       1.0
       81790       0.00      0.00      0.00       0.0
       81867       0.00      0.00      0.00       0.0
       82071       0.00      0.00      0.00       0.0
       83061       0.00      0.00      0.00       2.0
       83229       0.00      0.00      0.00       0.0
       83519       0.00      0.00      0.00       0.0
       83814       0.00      0.00      0.00       0.0
       84083       0.00      0.00      0.00       1.0
       84263       0.00      0.00      0.00       0.0
       84429       0.00      0.00      0.00       1.0
       84557       0.00      0.00      0.00       1.0
       84691       0.00      0.00      0.00       1.0
       84775       0.00      0.00      0.00       1.0
       84845       0.00      0.00      0.00       1.0
       85016       0.00      0.00      0.00       0.0
       85570       0.00      0.00      0.00       0.0
       85651       0.00      0.00      0.00       0.0
       85972       0.00      0.00      0.00       0.0
       86208       0.00      0.00      0.00       1.0
       86531       0.00      0.00      0.00       0.0
       86652       0.00      0.00      0.00       1.0
       87348       0.00      0.00      0.00       4.0
       87685       0.00      0.00      0.00       0.0
       88636       0.00      0.00      0.00       0.0
       88720       0.00      0.00      0.00       0.0
       88918       0.00      0.00      0.00       0.0
       89277       0.00      0.00      0.00       1.0
       90065       0.00      0.00      0.00       0.0
       90444       0.00      0.00      0.00       1.0
       90910       0.00      0.00      0.00       3.0
       91304       0.00      0.00      0.00       0.0
       91462       0.00      0.00      0.00       1.0
       91545       0.00      0.00      0.00       2.0
       91547       0.00      0.00      0.00       0.0
       91684       0.00      0.00      0.00       0.0
       92040       0.00      0.00      0.00       0.0
       92426       0.00      0.00      0.00       2.0
       92498       0.00      0.00      0.00       0.0
       92819       0.00      0.00      0.00       0.0
       93307       0.00      0.00      0.00       1.0
       93339       0.00      0.00      0.00       0.0
       93659       0.00      0.00      0.00       1.0
       94033       0.00      0.00      0.00       0.0
       94287       0.00      0.00      0.00       0.0
       94413       0.00      0.00      0.00       2.0
       94418       0.00      0.00      0.00       1.0
       95088       0.00      0.00      0.00       1.0
       95920       0.00      0.00      0.00       0.0
       96355       0.00      0.00      0.00       1.0
       96438       0.00      0.00      0.00       0.0
       96519       0.00      0.00      0.00       0.0
       96652       0.00      0.00      0.00       0.0
       97200       0.00      0.00      0.00       0.0
       97318       0.00      0.00      0.00       0.0
       97453       0.00      0.00      0.00       2.0
       97493       0.00      0.00      0.00       0.0
       97703       0.00      0.00      0.00       0.0
       97957       0.00      0.00      0.00       0.0
       97984       0.00      0.00      0.00       0.0
       98152       0.00      0.00      0.00       0.0
       98240       0.00      0.00      0.00       1.0
       98416       0.00      0.00      0.00       1.0
       98592       0.00      0.00      0.00       2.0
       98738       0.00      0.00      0.00       1.0
       99307       0.00      0.00      0.00       2.0
       99311       0.00      0.00      0.00       0.0
       99325       0.00      0.00      0.00       0.0

    accuracy                           0.00     180.0
   macro avg       0.00      0.00      0.00     180.0
weighted avg       0.00      0.00      0.00     180.0

In [20]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(Y_train, y_pred_train))

Accuracy: 1.0

In [21]:
from sklearn.metrics import confusion_matrix

print("\nConfusion Matrix:\n", confusion_matrix(Y_train, y_pred_train))

Confusion Matrix:
 [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]

In [22]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
num_trees = 200
#max_features = 3
kfold = KFold(n_splits=10, random_state=7, shuffle=True) #Bootstrap

model = RandomForestClassifier(n_estimators=num_trees,max_depth=5,  min_samples_leaf=5,max_features='sqrt')
results = cross_val_score(model, x, y, cv=kfold)
print(results.mean())

0.0

In [23]:
#AdaBoostClassifier
from sklearn.ensemble import AdaBoostClassifier

kfold = KFold(n_splits=10, random_state=7,shuffle=True) 
model1 = AdaBoostClassifier(n_estimators=100, random_state=7)
results = cross_val_score(model1, x, y, cv=kfold)
print(results.mean())

0.0

In [24]:
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y_train = le.fit_transform(Y_train)

In [28]:
model = XGBClassifier(n_estimators=90,max_depth=3)
model.fit(X_train, Y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=90, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [33]:
y_pred_test = model.predict(X_test)
predictions = [round(value) for value in y_pred_test]
predictions

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 237,
 237,
 0,
 0,
 0,
 237,
 0,
 0,
 0,
 0,
 0,
 237,
 0,
 237,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 237,
 0,
 0,
 0,
 0,
 0,
 237,
 0,
 0,
 0,
 0,
 237,
 0,
 237,
 237,
 0,
 0,
 0,
 237,
 0,
 0,
 0,
 0,
 237,
 0,
 0,
 237,
 237,
 237,
 237,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 237,
 237,
 237,
 0,
 0,
 237,
 237,
 0,
 237,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 237,
 0,
 237,
 237,
 0,
 0,
 237,
 0,
 0,
 0,
 237,
 0,
 0,
 237,
 0,
 0,
 0,
 0,
 0,
 0,
 237,
 0,
 0,
 237,
 0,
 0,
 0,
 0,
 237,
 0,
 0,
 237,
 0,
 0,
 237,
 0,
 237,
 0,
 0,
 237,
 0,
 0,
 0,
 0,
 237,
 0,
 237,
 0,
 0,
 0,
 0,
 0,
 237,
 0,
 237,
 0,
 0,
 237,
 237,
 0,
 237,
 0,
 0,
 0,
 0,
 0,
 0,
 237,
 0,
 0,
 237,
 237,
 0,
 0,
 237,
 0,
 0,
 0,
 0,
 0,
 0,
 237,
 0,
 0,
 237,
 0,
 0,
 237,
 237,
 0,
 0,
 237]

In [35]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 0.00%

In [36]:
import lightgbm as lgb
d_train = lgb.Dataset(X_train, label=Y_train)

In [37]:
params = {}
params['learning_rate'] = 0.002, # 0.1,0.3
params['boosting_type'] = 'gbdt' # dart
params['objective'] = 'binary'
params['metric'] = 'binary_logloss'
params['sub_feature'] = 0.5 
params['num_leaves'] = 10
params['min_data'] = 50
params['max_depth'] = 10

In [38]:
params

{'learning_rate': (0.002,),
 'boosting_type': 'gbdt',
 'objective': 'binary',
 'metric': 'binary_logloss',
 'sub_feature': 0.5,
 'num_leaves': 10,
 'min_data': 50,
 'max_depth': 10}

In [39]:
clf = lgb.train(params, d_train, 1400)

[LightGBM] [Info] Number of positive: 419, number of negative: 1
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001819 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 186
[LightGBM] [Info] Number of data points in the train set: 420, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.997619 -> initscore=6.037871
[LightGBM] [Info] Start training from score 6.037871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [40]:
y_pred = clf.predict(X_test)

In [41]:
predictions = [round(value) for value in y_pred]

In [42]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 0.00%