In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r'C:\Users\SHYAM SASHANK\OneDrive\Desktop\Data_Science\class_codes\Toyoto_Corrola.csv')
df

,Id,Model,Price,Age_08_04,KM,HP,Doors,Cylinders,Gears,Weight
0,1,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13500,23,46986,90,3,4,5,1165
1,2,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13750,23,72937,90,3,4,5,1165
2,3,ÊTOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13950,24,41711,90,3,4,5,1165
3,4,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,14950,26,48000,90,3,4,5,1165
4,5,TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors,13750,30,38500,90,3,4,5,1170
...,...,...,...,...,...,...,...,...,...,...
1431,1438,TOYOTA Corolla 1.3 16V HATCHB G6 2/3-Doors,7500,69,20544,86,3,4,5,1025
1432,1439,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,10845,72,19000,86,3,4,5,1015
1433,1440,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,8500,71,17016,86,3,4,5,1015
1434,1441,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,7250,70,16916,86,3,4,5,1015
1435,1442,TOYOTA Corolla 1.6 LB LINEA TERRA 4/5-Doors,6950,76,1,110,5,4,5,1114

In [3]:
from sklearn.metrics import r2_score
score = r2_score(df1["Age_08_04"], df["Price"])

NameError: name 'df1' is not defined

In [30]:
df1=df.drop(columns=["Model","Doors","Cylinders","Gears","Price","Id"])
df1.head()

   Age_08_04     KM  HP  Weight
0         23  46986  90    1165
1         23  72937  90    1165
2         24  41711  90    1165
3         26  48000  90    1165
4         30  38500  90    1170

In [31]:
y=df["Price"]
y

0       13500
1       13750
2       13950
3       14950
4       13750
        ...
1431     7500
1432    10845
1433     8500
1434     7250
1435     6950
Name: Price, Length: 1436, dtype: int64

In [32]:
df1.corr()

           Age_08_04        KM        HP    Weight
Age_08_04   1.000000  0.505672 -0.156622 -0.470253
KM          0.505672  1.000000 -0.333538 -0.028598
HP         -0.156622 -0.333538  1.000000  0.089614
Weight     -0.470253 -0.028598  0.089614  1.000000

In [33]:
import statsmodels.formula.api as smf
model=smf.ols('Price~Age_08_04+KM+HP+Weight', data=df).fit()

In [34]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.861
Method:                 Least Squares   F-statistic:                     2230.
Date:                Wed, 19 Jul 2023   Prob (F-statistic):               0.00
Time:                        20:30:03   Log-Likelihood:                -12386.
No. Observations:                1436   AIC:                         2.478e+04
Df Residuals:                    1431   BIC:                         2.481e+04
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -4014.6418    936.044     -4.289      0.000   -5850.808   -2178.476
Age_08_04   -122.4245      2.623    -46.668      0.000    -127.570    -117.278
KM            -0.0196      0.001    -16.271      0.000      -0.022      -0.017
HP            30.2119      2.539     11.897      0.000      25.230      35.193
Weight        18.5319      0.803     23.084      0.000      16.957      20.107
==============================================================================
Omnibus:                      197.115   Durbin-Watson:                   1.570
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1498.712
Skew:                          -0.384   Prob(JB):                         0.00
Kurtosis:                       7.946   Cond. No.                     2.05e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.05e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [35]:
from sklearn.linear_model import LinearRegression

In [36]:
lm=LinearRegression()
lm.fit(df1,y)

LinearRegression()

In [37]:
lm.coef_

array([-1.22424469e+02, -1.96473360e-02,  3.02119268e+01,  1.85318677e+01])

In [38]:
lm.intercept_

-4014.641772451112

In [39]:
lm.predict([[10,38500,90,1170]])

C:\Users\SHYAM SASHANK\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([18406.04967314])

In [40]:
a=(10*-1.22424469e+02)+(38500*-1.96473360e-02)+(90*3.02119268e+01)+(1170*1.85318677e+01)+(-4014.641772451112)
a

18406.049722548887

In [41]:
from sklearn.metrics import r2_score
score = r2_score(df1["Age_08_04"], df["Price"])
print("The accuracy of our model is {}%".format(round(score, 2) *100))

The accuracy of our model is -36797815.0%

In [42]:
score = r2_score(df1["HP"], df["Price"])
print("The accuracy of our model is {}%".format(round(score, 2)))

The accuracy of our model is -562225.75%